### ISSUE TITLE
[Feature Request] 推荐/热门页面增加清爽模式

### ISSUE THREAD

**Issue by youngerstar** [magicdawn/Bilibili-Gate#155]
在推荐页面和热门页面增加清爽模式，去除视觉干扰元素（比如播放量/点赞量/弹幕量/标签/up头像/up ID），专注于信息本身。
以下是示意图：
**开启前**
![Image](https://github.com/user-attachments/assets/10874aba-9dd3-4b52-90b3-b93bb3641d5f)
**开启后**
![Image](https://github.com/user-attachments/assets/3458efd6-5e03-4544-be41-3635cbee62c1)

**Comment by magicdawn** [comment]
暂不考虑

如你所说, 可以使用 uBlock Origin / [Stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) 定制, 如

```css
.bilibili-gate-video-grid[data-tab="hot"] {
   .bili-video-card__stats--left {
     visibility: hidden !important;
   }
}
```


注: `data-tab` 添加自 fdbfd54 ,未 release.
